export const CREATE_INGREDIANT = "CREATE_INGREDIANT";
export const UPDATE_INGREDIANT = "UPDATE_INGREDIANT";
export const FETCH_INGREDIANTS = "FETCH_INGREDIANTS";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";